### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [intercom/official-gtm-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) An error "Attempting to execute non-function methodFunc." is thrown when trying to run the tests. Please resolve the issue.
![intercom_error](https://user-images.githubusercontent.com/53495700/87719921-fa6a0600-c768-11ea-8493-0613078aadc6.png)

**Comment by alonre** [comment]
Thank you for the feedback @praveena-pappu !
We've beefed up our tests and made sure they all pass.
We've updated `metadata.yaml` to point to the latest version as well.

Is there anything else we should do to get this reviewed and published?
